position: bottom

sidebar:
  theme: solarized-light
  prefix_mode: true
  header:
    text: "none"
  colors:
    inactive_fg: "#586e75"
    disclosure_expanded: "none"
    disclosure_collapsed: "none"

groups:
  - name: "Default"
    pattern: ".*"
    theme:
      bg: "#b0caab"
      fg: "#2e4a2e"
      active_bg: "#edd78a"
      active_fg: "#5b5017"

pane_header:
  inactive_fg: "#586e75"

widgets:
  session:
    enabled: true
    show_session: false
    show_kube_context: true
    kube_icon: "🛞"
    position: bottom
    pin: true
    fg: "#586e75"
    divider: "─"
    divider_fg: "#93a1a1"
    margin_bottom: 1

indicators:
  bell:
    enabled: false
  activity:
    enabled: false
  busy:
    enabled: false
  input:
    enabled: false
